### PR TITLE
Submitting feb proposal for BPF implementation

### PR DESCRIPTION
**Pull request by nelcolon**

### CODE REVIEW

**Review by luyzdeleon — COMMENTED** [review]
How does the entire network benefit from this proposal?

**Comment by nelcolon** [comment]
This only helps our GKE cluster. We could adapt the process and rules we develop for us to eventually release to the community for whoever wants to use a setup similar to us.

**Comment by luyzdeleon** [comment]
Why not increase the scope of this proposal and add that.

**Comment by nelcolon** [comment]
Nice suggestion. Let me add it to the proposal.

**Pull request merged**
